defmodule DrawbridgeCore.Lockfile do
  @moduledoc """
  Reads, writes, and overlays `drawbridge.lock` files for reproducible image pinning.

  Lock format (YAML):

      # Auto-generated by drawbridge lock. Do not edit.
      locked_at: "2026-03-23T12:00:00Z"
      images:
        postgres:
          tag: "postgis/postgis:17-3.5"
          digest: "sha256:abc123..."
          locked_at: "2026-03-23T12:00:00Z"
  """

  @lock_filename "drawbridge.lock"

  @doc "Load and parse a YAML lockfile. Returns `{:ok, lock_data}` or `{:error, reason}`."
  def load(path) do
    case YamlElixir.read_from_file(path) do
      {:ok, raw} ->
        {:ok, parse(raw)}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc "Write lock data to a YAML file."
  def write(path, lock_data) do
    yaml = serialize(lock_data)
    File.write(path, yaml)
  end

  @doc """
  Overlay lockfile digests onto a config.

  For each service whose image tag matches a lockfile entry, populates `image_digest`.
  """
  def overlay(%DrawbridgeCore.Config{} = config, lock_data) do
    images = lock_data[:images] || %{}

    updated_services =
      Map.new(config.services, fn {name, svc} ->
        case Map.get(images, name) do
          %{tag: tag, digest: digest} when tag == svc.image ->
            {name, %{svc | image_digest: digest}}

          _ ->
            {name, svc}
        end
      end)

    %{config | services: updated_services}
  end

  @doc """
  Find, load, and overlay a lockfile for the given config path.

  Convenience that combines `find_lockfile/1`, `load/1`, and `overlay/2`.
  Returns the config unchanged if no lockfile exists or loading fails.
  """
  def load_and_overlay(%DrawbridgeCore.Config{} = config, config_path) do
    case find_lockfile(config_path) do
      {:ok, lock_path} ->
        case load(lock_path) do
          {:ok, lock_data} -> overlay(config, lock_data)
          {:error, _} -> config
        end

      :none ->
        config
    end
  end

  @doc "Look for `drawbridge.lock` in the same directory as the config file."
  def find_lockfile(config_path) do
    lock_path = config_path |> Path.dirname() |> Path.join(@lock_filename)

    if File.exists?(lock_path) do
      {:ok, lock_path}
    else
      :none
    end
  end

  defp parse(raw) do
    images =
      (raw["images"] || %{})
      |> Map.new(fn {name, entry} ->
        {name,
         %{
           tag: entry["tag"],
           digest: entry["digest"],
           locked_at: entry["locked_at"]
         }}
      end)

    %{
      locked_at: raw["locked_at"],
      images: images
    }
  end

  defp serialize(lock_data) do
    lines = [
      "# Auto-generated by drawbridge lock. Do not edit.",
      "locked_at: \"#{lock_data.locked_at}\"",
      "images:"
    ]

    image_lines =
      lock_data.images
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.flat_map(fn {name, entry} ->
        [
          "  #{name}:",
          "    tag: \"#{entry.tag}\"",
          "    digest: \"#{entry.digest}\"",
          "    locked_at: \"#{entry.locked_at}\""
        ]
      end)

    Enum.join(lines ++ image_lines, "\n") <> "\n"
  end
end
