defmodule Mix.Tasks.Drawbridge.Up do
  @moduledoc "Start the Drawbridge proxy and container orchestrator."

  if Code.ensure_loaded?(Mix.Task) do
    use Mix.Task
  end

  require Logger

  def run(args) do
    {opts, _, _} =
      OptionParser.parse(args,
        switches: [config: :string, no_dns: :boolean, tui: :boolean, local: :keep],
        aliases: [c: :config, l: :local]
      )

    config_path = opts[:config] || DrawbridgeCli.find_config()
    local_services = Keyword.get_values(opts, :local)

    Logger.info("[Drawbridge] Loading config from #{config_path}")

    case DrawbridgeCore.Config.load(config_path) do
      {:ok, config} ->
        boot(config, opts, config_path, local_services)

      {:error, reason} ->
        IO.puts(:stderr, "error: Failed to load config: #{inspect(reason)}")
        System.halt(1)
    end
  end

  defp boot(config, opts, config_path, local_services) do
    DrawbridgeCli.ensure_started()

    unknown = Enum.reject(local_services, &Map.has_key?(config.services, &1))

    if unknown != [] do
      IO.puts(:stderr, "error: Unknown services: #{Enum.join(unknown, ", ")}")
      System.halt(1)
    end

    data_dir = Application.get_env(:drawbridge_core, :data_dir, "~/.drawbridge")

    {:ok, certs} = DrawbridgeCore.CertManager.ensure_certs(config.domain, data_dir)
    Logger.info("[Drawbridge] TLS certs ready at #{certs.cert}")

    unless opts[:no_dns] do
      DrawbridgeCore.DnsManager.setup_hosts(config)
    end

    if local_services != [] do
      generate_local_env(config, local_services)

      Enum.each(local_services, fn name ->
        IO.puts("[Drawbridge] Local: #{name} (not managed, running from source)")
      end)
    end

    # Resolve ECR image tags (no-tag → latest from ECR API)
    config = DrawbridgeCore.ImageResolver.resolve_config(config)

    orchestrated_config = DrawbridgeCore.Config.exclude_services(config, local_services)
    DrawbridgeCore.Orchestrator.start(orchestrated_config, config_path: config_path)

    print_status(orchestrated_config, config, local_services)

    Logger.info("[Drawbridge] Proxy running. Hit Ctrl+C to stop.")

    if opts[:tui] do
      DrawbridgeTui.start(config.domain)
    else
      Process.sleep(:infinity)
    end
  end

  defp generate_local_env(config, local_services) do
    env_lines =
      local_services
      |> Enum.flat_map(fn name ->
        case Map.fetch(config.services, name) do
          {:ok, svc} -> Enum.map(svc.env || %{}, fn {k, v} -> "#{k}=#{v}" end)
          :error -> []
        end
      end)
      |> Enum.uniq()
      |> Enum.sort()

    content =
      [
        "# Generated by drawbridge up --local",
        "# Source this in your local dev environment:",
        "#   source .env.drawbridge",
        ""
        | env_lines
      ]
      |> Enum.join("\n")

    File.write!(".env.drawbridge", content <> "\n")
    IO.puts("[Drawbridge] Generated .env.drawbridge for local development")
  end

  defp print_service_row(name, svc, state) do
    ports = Enum.map_join(svc.ports, ", ", fn {h, c} -> "#{h}:#{c}" end)

    row =
      String.pad_trailing(to_string(name), 20) <>
        String.pad_trailing(svc.hostname, 30) <>
        String.pad_trailing(ports, 20) <>
        state

    IO.puts("  #{row}")
  end

  defp print_status(_orchestrated_config, full_config, local_services) do
    IO.puts("")
    IO.puts("  Drawbridge is up")
    IO.puts("  Domain: *.#{full_config.domain}")
    IO.puts("")

    header =
      String.pad_trailing("Service", 20) <>
        String.pad_trailing("Hostname", 30) <> String.pad_trailing("Ports", 20) <> "State"

    IO.puts("  #{header}")
    IO.puts("  #{String.duplicate("─", 80)}")

    local_set = MapSet.new(local_services)

    Enum.each(full_config.services, fn {name, svc} ->
      state = if MapSet.member?(local_set, name), do: "local", else: "sleeping"
      print_service_row(name, svc, state)
    end)

    IO.puts("")
  end
end
