defmodule DrawbridgeCore.LockfileTest do
  use ExUnit.Case, async: true

  alias DrawbridgeCore.Lockfile
  alias DrawbridgeCore.Config
  alias DrawbridgeCore.Config.Service

  @lock_yaml """
  # Auto-generated by drawbridge lock. Do not edit.
  locked_at: "2026-03-23T12:00:00Z"
  images:
    postgres:
      tag: "postgres:16"
      digest: "sha256:abc123"
      locked_at: "2026-03-23T12:00:00Z"
    redis:
      tag: "redis:7"
      digest: "sha256:def456"
      locked_at: "2026-03-23T12:00:00Z"
  """

  setup do
    tmp = System.tmp_dir!()
    dir = Path.join(tmp, "drawbridge_lock_test_#{:rand.uniform(100_000)}")
    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)
    {:ok, dir: dir}
  end

  test "load/1 parses a lockfile", %{dir: dir} do
    path = Path.join(dir, "drawbridge.lock")
    File.write!(path, @lock_yaml)

    assert {:ok, lock_data} = Lockfile.load(path)
    assert lock_data.locked_at == "2026-03-23T12:00:00Z"
    assert map_size(lock_data.images) == 2
    assert lock_data.images["postgres"].digest == "sha256:abc123"
    assert lock_data.images["redis"].tag == "redis:7"
  end

  test "load/1 returns error for missing file" do
    assert {:error, _} = Lockfile.load("/tmp/nonexistent_lockfile_#{:rand.uniform()}.lock")
  end

  test "write/2 and load/1 round-trip", %{dir: dir} do
    path = Path.join(dir, "drawbridge.lock")

    lock_data = %{
      locked_at: "2026-03-23T14:00:00Z",
      images: %{
        "pg" => %{tag: "postgres:16", digest: "sha256:aaa", locked_at: "2026-03-23T14:00:00Z"}
      }
    }

    assert :ok = Lockfile.write(path, lock_data)
    assert {:ok, loaded} = Lockfile.load(path)
    assert loaded.images["pg"].digest == "sha256:aaa"
    assert loaded.images["pg"].tag == "postgres:16"
  end

  test "overlay/2 injects digests into matching services" do
    config = %Config{
      domain: "dev.local",
      idle_timeout: 300,
      max_containers: 8,
      services: %{
        "postgres" => %Service{
          name: "postgres",
          image: "postgres:16",
          hostname: "pg.dev.local",
          ports: [{5432, 5432}]
        },
        "redis" => %Service{
          name: "redis",
          image: "redis:7",
          hostname: "redis.dev.local",
          ports: [{6379, 6379}]
        }
      }
    }

    lock_data = %{
      locked_at: "2026-03-23T12:00:00Z",
      images: %{
        "postgres" => %{
          tag: "postgres:16",
          digest: "sha256:abc123",
          locked_at: "2026-03-23T12:00:00Z"
        },
        "redis" => %{tag: "redis:7", digest: "sha256:def456", locked_at: "2026-03-23T12:00:00Z"}
      }
    }

    result = Lockfile.overlay(config, lock_data)
    assert result.services["postgres"].image_digest == "sha256:abc123"
    assert result.services["redis"].image_digest == "sha256:def456"
  end

  test "overlay/2 skips services with non-matching tags" do
    config = %Config{
      domain: "dev.local",
      idle_timeout: 300,
      max_containers: 8,
      services: %{
        "postgres" => %Service{
          name: "postgres",
          image: "postgres:17",
          hostname: "pg.dev.local",
          ports: [{5432, 5432}]
        }
      }
    }

    lock_data = %{
      locked_at: "2026-03-23T12:00:00Z",
      images: %{
        "postgres" => %{
          tag: "postgres:16",
          digest: "sha256:abc123",
          locked_at: "2026-03-23T12:00:00Z"
        }
      }
    }

    result = Lockfile.overlay(config, lock_data)
    assert result.services["postgres"].image_digest == nil
  end

  test "find_lockfile/1 finds lockfile next to config", %{dir: dir} do
    config_path = Path.join(dir, "drawbridge.yml")
    lock_path = Path.join(dir, "drawbridge.lock")
    File.write!(config_path, "domain: test")
    File.write!(lock_path, @lock_yaml)

    assert {:ok, ^lock_path} = Lockfile.find_lockfile(config_path)
  end

  test "find_lockfile/1 returns :none when no lockfile", %{dir: dir} do
    config_path = Path.join(dir, "drawbridge.yml")
    File.write!(config_path, "domain: test")

    assert :none = Lockfile.find_lockfile(config_path)
  end
end
